### This is a tutorial on numpy

Please check it out!

In [1]:
from numpy import *
array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
array([1,2,3,4,5])/5

array([0, 0, 0, 0, 1])

#### Add a period after numbers in an array to divide as floats


In [3]:
array([1.,2.,3.,4.,5.])/5

array([ 0.2,  0.4,  0.6,  0.8,  1. ])

In [4]:
array([1,2,3,4,5],dtype = 'f')/5

array([ 0.2       ,  0.40000001,  0.60000002,  0.80000001,  1.        ], dtype=float32)

#### Easily perform a dot product using the dot() function on two arrays -


In [5]:
dot(array([1,2,3,4,5]),array([2,3,4,5,6]))

70